apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 30
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "256m"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "256m"
          ports:
            - containerPort: 80
